export const GET_POSTS = 'GET_POSTS';

export const API_REQUEST_GENERAL_CATEGORIES = 'API_REQUEST_GENERAL_CATEGORIES';

export const API_REQUEST_CATEGORIES = 'API_REQUEST_CATEGORIES'

export const API_REQUEST_CATEGORY_ADD_ITEMS = 'API_REQUEST_CATEGORY_ADD_ITEMS'

export const ADD_ID_CATEGORY = 'ADD_ID_CATEGORY';

export const CHANGING_THE_FLAG = 'CHANGING_THE_FLAG'

export const CHANGING_PAGINATION = 'CHANGING_PAGINATION'
