import Head from 'next/head'
import Image from 'next/image'
import React, {useEffect, useState} from 'react';
import {useDispatch, useSelector} from 'react-redux';
import {fetchposts} from '../store/actions/postActions';
import Main from './component/Main/Main';
import Filter from './component/Filter/Filter'
import Link from "next/link";
import MainContainer from "./component/MainContainer/MainContainer";
import styles from '../styles/Home.module.css'

export default function Home({baseUrl, array, arrayTwo}) {

    const [auth, setAuth] = useState(() => {
        return {
            auth: false,
            userName: ''
        }
    })

    const {posts} = useSelector(state => state.post);

    const dispatch = useDispatch();

    const refreshToken = (token) => {
        const baseUrlTwo = `https://bion.biz-mark.ru`;
        fetch(`${baseUrlTwo}/api/v1/auth/refresh`, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`,
            }
        })
            .then((response) => response.json())
            .then((data) => {
                    console.log((data));
                }
            )
            .catch((error) => {
                console.error('Error:', error);
            });
    }

    useEffect(() => {
        const baseUrl = `https://bion.biz-mark.ru/api/v1/account`;
        const token = localStorage.getItem('tokenAuth');
        let idCard = '';

        fetch(baseUrl, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`,
            }
        })
            .then((response) => response.json())
            .then((data) => {
                    idCard = localStorage.getItem('cardUserId');
                    console.log(idCard)
                    setAuth(prev => {
                        return {
                            ...prev,
                            userName: data.data.name,
                            auth: true
                        }
                    })
                }
            )
            .catch((error) => {
                console.error('Error:', error);
                if (token !== null) {
                    refreshToken(token);
                }
            });
        dispatch(fetchposts());
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <header>
                {/*<Link href={`/account/login`}>*/}
                {/*    <a className={styles.filter__wordButton}>Вход</a>*/}
                {/*</Link>*/}
                {/*/*/}
                {/*<Link href={`/account/register`}>*/}
                {/*    <a className={styles.filter__wordButton}>Регистрация</a>*/}
                {/*</Link>*/}
                {/*/!*<button>корзина</button>*!/*/}
                {/*<div>*/}
                {/*    ____________________________________________________________*/}
                {/*</div>*/}
                {/*<p>*/}
                {/*    {auth.auth ? auth.userName : 'Авторизуйтесь!'}*/}
                {/*</p>*/}
            </header>
            <MainContainer url={baseUrl} items={array.data}>
                <main className={styles.main}>
                    {/*<h1 className={styles.title}>*/}
                    {/*    Welcome to <a href="https://nextjs.org">Next.js!</a>*/}
                    {/*</h1>*/}
                    {/*<Filter/>*/}
                    <Main items={array.data}/>
                </main>
            </MainContainer>
            {/*<footer className={styles.footer}>*/}
            {/*</footer>*/}
        </div>
    )
}

export async function getServerSideProps({params}) {
    const baseUrl = `https://bion.biz-mark.ru/api/v1/general`;
    const response = await fetch(`${baseUrl}/categories`);
    const array = await response.json();

    return {
        props: {baseUrl,array} // will be passed to the page component as props
    }
}
