import Head from 'next/head'
import React, {useEffect, useState} from 'react';
import {useDispatch, useSelector} from 'react-redux';
import {fetchposts} from '../store/actions/postActions';
import Main from './component/Main/Main';
import MainContainer from "./component/MainContainer/MainContainer";
import styles from '../styles/Home.module.css'

export default function Home({baseUrl, array, arrayItems}) {

    const [auth, setAuth] = useState(() => {
        return {
            auth: false,
            userName: ''
        }
    })

    const {posts} = useSelector(state => state.post);

    const dispatch = useDispatch();

    const refreshToken = (token) => {
        const baseUrlTwo = `https://bion.biz-mark.ru`;
        fetch(`${baseUrlTwo}/api/v1/auth/refresh`, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`,
            }
        })
            .then((response) => response.json())
            .then((data) => {
                    console.log((data));
                }
            )
            .catch((error) => {
                console.error('Error:', error);
            });
    }

    useEffect(() => {
        const cardUserId = localStorage.getItem('cardUserId');
        const baseUrl = `https://bion.biz-mark.ru/api/v1/account`;
        const token = localStorage.getItem('tokenAuth');
        let idCard = '';

        fetch(baseUrl, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${token}`,
            }
        })
            .then((response) => response.json())
            .then((data) => {
                    idCard = localStorage.getItem('cardUserId');
                    console.log(idCard)
                    setAuth(prev => {
                        return {
                            ...prev,
                            userName: data.data.name,
                            auth: true
                        }
                    })
                }
            )
            .catch((error) => {
                console.error('Error:', error);
                if (token !== null) {
                    refreshToken(token);
                }
            });
        dispatch(fetchposts());
        console.log(cardUserId);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <header>
            </header>
            <MainContainer url={baseUrl} arrayItems={arrayItems} items={array.data}>
                <main className={styles.main}>
                    <Main items={array.data}/>
                </main>
            </MainContainer>
            {/*<footer className={styles.footer}>*/}
            {/*</footer>*/}
        </div>
    )
}

export async function getServerSideProps({params}) {
    const baseUrl = `https://bion.biz-mark.ru/api/v1/general`;
    const response = await fetch(`${baseUrl}/categories`);
    const array = await response.json();
    const responseTwo = await fetch(`${baseUrl}/products`);
    const arrayItems = await responseTwo.json();

    return {
        props: {baseUrl, array, arrayItems} // will be passed to the page component as props
    }
}
